
version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-candidatos
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Totus@123"
      MSSQL_DBNAME: "crudCandidatos"
    ports:
      - "1450:1433"
    networks:
      - crudcandidatos-net
    restart: unless-stopped

networks:
  crudcandidatos-net:
    driver: bridge
